#!/usr/bin/env python3
"""Build a C-only i960 image with explicitly approved original data ranges."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def number(value: str | int) -> int:
    return int(value, 0) if isinstance(value, str) else value


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated", required=True, type=Path)
    parser.add_argument("--original", required=True, type=Path)
    parser.add_argument("--ranges", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--build-manifest", required=True, type=Path)
    args = parser.parse_args()

    config = json.loads(args.ranges.read_text(encoding="utf-8"))
    image_size = number(config["image_size"])
    generated = args.generated.read_bytes()
    original = args.original.read_bytes()
    if len(generated) > image_size:
        raise SystemExit("generated image exceeds configured i960 image size")
    if len(original) != image_size:
        raise SystemExit(f"original image is {len(original)} bytes; expected {image_size}")

    image = bytearray([number(config["fill_byte"])]) * image_size
    image[:len(generated)] = generated
    copied = []
    for entry in config.get("ranges", []):
        start = number(entry["start"])
        end = number(entry["end"])
        if start < len(generated):
            raise SystemExit(f"approved data range overlaps generated code: {entry['name']}")
        data = original[start:end]
        digest = hashlib.sha256(data).hexdigest()
        if digest != entry["sha256"]:
            raise SystemExit(f"approved data hash mismatch: {entry['name']}")
        image[start:end] = data
        copied.append({**entry, "bytes": end - start})

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(image)
    build = {
        "schema_version": 1,
        "generated_code_bytes": len(generated),
        "generated_code_sha256": hashlib.sha256(generated).hexdigest(),
        "output_sha256": hashlib.sha256(image).hexdigest(),
        "fill_byte": number(config["fill_byte"]),
        "approved_data_bytes": sum(entry["bytes"] for entry in copied),
        "approved_ranges": copied,
    }
    args.build_manifest.write_text(json.dumps(build, indent=2) + "\n", encoding="utf-8")
    print(
        f"Built clean i960 image: {len(generated)} generated bytes, "
        f"{build['approved_data_bytes']} approved data bytes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
