#!/usr/bin/env python3
"""Embed extracted stage arenas into the kernel and the Godot mirror.

Reads the per-stage outputs of extract_stage_geometry.py (boxes + heightfield)
and writes:

  <godot>/native/kernels/stage_arenas.h   box + heightfield arrays and the
                                          RV_ARENAS table the kernel includes
  <godot>/scripts/von_stage_boxes.gd      VonStageBoxes.BOXES mirror for Godot

Terrain stages are those whose heightfield is non-trivial (a configurable
range); the rest keep floor y = 0 and use collision boxes only.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

STAGE_NAMES = ["FLOODED CITY", "AIRPORT", "WATERFRONT", "GREEN HILLS", "RUINS",
               "SECRET BASE", "SPACE DOCK", "MOON BASE", "DEATH TRAP", "NIRVANA"]
HALF = 320.0
# Airport's two central raised slabs are movement-confirmed pads, not blocking
# solids (recovered_stage_obstacle_boxes.c).  Geometry extraction supplies the
# bounds but not the gameplay kind, so retain that recovered semantic here.
PAD_OBAS = {1: {0x00800126, 0x0080009D}}


def obstacle_kind(stage: int, box: dict) -> int:
    return 1 if int(box["oba"], 0) in PAD_OBAS.get(stage, set()) else 0


def fmt(value: float) -> str:
    text = f"{value:.4g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def load(input_dir: Path, stage: int):
    boxes = json.loads((input_dir / f"stage_{stage:02d}_boxes.json").read_text())
    seen = {}
    for box in boxes:
        seen.setdefault((tuple(box["min"]), tuple(box["max"])), box)
    boxes = list(seen.values())
    height = json.loads((input_dir / f"stage_{stage:02d}_heightfield.json").read_text())
    return boxes, height


def is_terrain(grid: list[list[float]], deviation: float = 4.0,
               fraction: float = 0.10) -> bool:
    values = [v for row in grid for v in row]
    values.sort()
    median = values[len(values) // 2]
    raised = sum(1 for v in values if abs(v - median) > deviation)
    return raised / len(values) >= fraction


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--godot-dir", type=Path, required=True)
    args = parser.parse_args()

    header: list[str] = [
        "/* Generated by von-arcade-decomp/von/tools/embed_stage_arenas.py.",
        " * Stage arena boxes and heightfields from the polygon-ROM extractor. */",
        "#pragma once",
        "",
    ]
    gd: list[str] = [
        "class_name VonStageBoxes",
        "extends RefCounted",
        "# Generated by von-arcade-decomp/von/tools/embed_stage_arenas.py.",
        "# Render-measured collision boxes per stage ordinal (kernel mirror).",
        "",
        "const BOXES := {",
    ]
    table: list[str] = ["static const rv_arena RV_ARENAS[] = {"]

    for stage in range(10):
        boxes, height = load(args.input_dir, stage)
        grid = height["grid"]
        terrain = is_terrain(grid)

        if boxes:
            header.append(f"static const rv_box RV_BOXES_S{stage}[] = {{")
            for b in boxes:
                header.append(f"    {{{b['min'][0]}, {b['min'][1]}, {b['min'][2]}, "
                              f"{b['max'][0]}, {b['max'][1]}, {b['max'][2]}, "
                              f"{obstacle_kind(stage, b)}}},")
            header.append("};")
            box_ref, box_count = f"RV_BOXES_S{stage}", f"RV_BOXES_S{stage}_COUNT"
            header.append(f"#define {box_count} "
                          f"((uint32_t)(sizeof(RV_BOXES_S{stage}) / sizeof(rv_box)))")
        else:
            box_ref, box_count = "NULL", "0u"

        if terrain:
            n = height["n"]
            header.append(f"static const float RV_TERRAIN_S{stage}[{n * n}] = {{")
            for row in grid:
                header.append("    " + ", ".join(fmt(v) for v in row) + ",")
            header.append("};")
            terrain_ref, terrain_n = f"RV_TERRAIN_S{stage}", f"{n}u"
        else:
            terrain_ref, terrain_n = "NULL", "0u"

        table.append(f"    /* {stage} {STAGE_NAMES[stage]:<12} */ "
                     f"{{{box_ref}, {box_count}, {HALF}f, 0.0f, {terrain_ref}, {terrain_n}}},")

        entries = ", ".join(
            "{\"oba\": %d, \"kind\": %d, \"min\": Vector3(%d, %d, %d), "
            "\"max\": Vector3(%d, %d, %d)}"
            % (int(b["oba"], 0), obstacle_kind(stage, b), *b["min"], *b["max"])
            for b in boxes)
        gd.append(f"\t{stage}: [{entries}],")

    table.append("};")
    header.insert(4, "")
    header.extend(table)
    gd.append("}")

    (args.godot_dir / "native/kernels/stage_arenas.h").write_text("\n".join(header) + "\n")
    (args.godot_dir / "scripts/von_stage_boxes.gd").write_text("\n".join(gd) + "\n")
    print("wrote stage_arenas.h and von_stage_boxes.gd")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
