#!/usr/bin/env python3
"""Emit the kernel's per-fighter projectile damage table.

Reads ``von/i960/weapon-damage-type-map.json`` (``fighter_types``: the recovered
damage-table index per fighter/weapon) and ``von/i960/damage-table.json`` (the
205 records at runtime ``0x565ed0``), and writes
``<godot>/native/kernels/weapon_damage.h``: for every roster fighter, the
LEFT/CENTER/RIGHT damage-table index and the record's raw damage, impulse, and
clamp bounds.

Evidence: ``probe_ordnance_id.lua`` (with fighter selection) reads byte 0 of the
player's ordnance record at spawn while firing one weapon per window; the hit
applier indexes ``table[type*16]`` with it.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Kernel roster order (RV_FIGHTER_COUNT rows).
FIGHTER_ORDER = ("TEMJIN", "VIPER2", "BELGDOR", "RAIDEN", "DORKAS", "FEIYEN",
                 "APHARMD", "BALBASBOW")


def build_rows(types: dict, records: dict):
    """Return one row per roster fighter: (type, raw, impulse, min, max) x3."""
    rows = []
    for fighter in FIGHTER_ORDER:
        row = []
        for entry in types[fighter]:
            if entry is None:
                row.append((-1, 0, 0.0, 0, 999))
                continue
            record = records[entry]
            row.append((entry, int(round(record["damage"])), float(record["impulse"]),
                        int(record["param2"]), int(record["param3"])))
        rows.append(row)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path,
                        default=Path("von/i960/weapon-damage-type-map.json"))
    parser.add_argument("--table", type=Path,
                        default=Path("von/i960/damage-table.json"))
    parser.add_argument("--godot-dir", type=Path)
    parser.add_argument("--output", type=Path,
                        help="default <godot>/native/kernels/weapon_damage.h")
    args = parser.parse_args()
    if args.output is None and args.godot_dir is None:
        parser.error("provide --godot-dir or --output")

    types = json.loads(args.map.read_text())["fighter_types"]
    records = {r["index"]: r for r in json.loads(args.table.read_text())["records"]}
    rows = build_rows(types, records)

    output = args.output or (args.godot_dir / "native" / "kernels" / "weapon_damage.h")
    lines = [
        "/* Generated by von-arcade-decomp/von/tools/emit_weapon_damage_header.py.",
        " * Per-fighter projectile damage-table index (LEFT, CENTER, RIGHT) and the",
        " * record at that index (raw damage, impulse, clamp min/max). Index -1 means",
        " * the slot has no typed projectile (a melee/contact attack). Recovered by",
        " * probe_ordnance_id.lua per fighter; table 0x565ed0. */",
        "#pragma once",
        "",
        f"#define VON_WEAPON_DAMAGE_FIGHTERS {len(rows)}",
        "",
        "/* [fighter][weapon L,C,R] damage-table index (-1 = no typed projectile). */",
        "static const int VON_WEAPON_DAMAGE_TYPE[VON_WEAPON_DAMAGE_FIGHTERS][3] = {",
    ]
    labels = ("LEFT", "CENTER", "RIGHT")
    for fighter, row in zip(FIGHTER_ORDER, rows):
        lines.append(f"    {{ /* {fighter} */")
        for slot, (index, _d, _i, _mn, _mx) in zip(labels, row):
            lines.append(f"        {index:4d},  /* {slot} */")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("/* [fighter][weapon] raw damage (working-health units / 10 in HUD %). */")
    lines.append("static const int VON_WEAPON_DAMAGE_RAW[VON_WEAPON_DAMAGE_FIGHTERS][3] = {")
    for fighter, row in zip(FIGHTER_ORDER, rows):
        values = ", ".join(f"{record[1]:4d}" for record in row)
        lines.append(f"    {{ {values} }},  /* {fighter} */")
    lines.append("};")
    lines.append("")
    lines.append("/* [fighter][weapon] record impulse, and clamp bounds param2/param3. */")
    lines.append("static const float VON_WEAPON_DAMAGE_IMPULSE[VON_WEAPON_DAMAGE_FIGHTERS][3] = {")
    for fighter, row in zip(FIGHTER_ORDER, rows):
        values = ", ".join(f"{record[2]:+.2f}f" for record in row)
        lines.append(f"    {{ {values} }},  /* {fighter} */")
    lines.append("};")
    lines.append("static const int VON_WEAPON_DAMAGE_MIN[VON_WEAPON_DAMAGE_FIGHTERS][3] = {")
    for fighter, row in zip(FIGHTER_ORDER, rows):
        values = ", ".join(f"{record[3]:4d}" for record in row)
        lines.append(f"    {{ {values} }},  /* {fighter} */")
    lines.append("};")
    lines.append("static const int VON_WEAPON_DAMAGE_MAX[VON_WEAPON_DAMAGE_FIGHTERS][3] = {")
    for fighter, row in zip(FIGHTER_ORDER, rows):
        values = ", ".join(f"{record[4]:4d}" for record in row)
        lines.append(f"    {{ {values} }},  /* {fighter} */")
    lines.append("};")
    lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
