#!/usr/bin/env python3
"""Emit the kernel's per-fighter weapon timing table from the profile block.

Reads ``von/i960/weapon-params.json`` (``dump_weapon_params.py``) and writes
``<godot>/native/kernels/weapon_timing.h``: for every roster fighter, the
startup/active/recovery frame counts of its three weapons, in the kernel's
LEFT/CENTER/RIGHT order.

Evidence: the action-duration writer at i960 ``0x30660`` selects, per action
(``object+0x174`` = 1/2/3) and phase (``object+0x176`` = 0/1/2), a duration from
the profile block and counts ``object+0x17e`` up to it.  The column labels
(1=right, 2=left, 3=center) come from the live-pinned cooldown timers in
``dump_weapon_params.py``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# JSON key -> kernel weapon column. The kernel's RV_WEAPONS order is L, C, R.
WEAPON_ORDER = ("left", "center", "right")
FIGHTER_ORDER = ("TEMJIN", "VIPER2", "BELGDOR", "RAIDEN", "DORKAS", "FEIYEN",
                 "APHARMD", "BALBASBOW", "JAGUARANDI", "Z-GRADT")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--params", type=Path,
                        default=Path("von/i960/weapon-params.json"))
    parser.add_argument("--godot-dir", type=Path,
                        help="Godot project root (default output dir)")
    parser.add_argument("--output", type=Path,
                        help="override the output path (default <godot>/native/kernels/weapon_timing.h)")
    args = parser.parse_args()
    if args.output is None and args.godot_dir is None:
        parser.error("provide --godot-dir or --output")

    data = json.loads(args.params.read_text())
    fighters = {f["fighter"]: f for f in data["fighters"]}
    missing = [n for n in FIGHTER_ORDER if n not in fighters]
    if missing:
        raise SystemExit(f"weapon-params.json is missing fighters: {missing}")

    lines = [
        "/* Generated by von-arcade-decomp/von/tools/emit_weapon_timing_header.py.",
        " * Per-fighter weapon action timing (startup/active/recovery frames),",
        " * recovered from the i960 profile block +0x5e8.. and the action-duration",
        " * writer at 0x30660. Weapon order is LEFT, CENTER, RIGHT. */",
        "#pragma once",
        "",
        f"#define VON_WEAPON_TIMING_FIGHTERS {len(FIGHTER_ORDER)}",
        "#define VON_WEAPON_TIMING_PHASES 3",
        "",
        "/* [fighter][weapon L,C,R][phase startup,active,recovery] */",
        "static const int VON_WEAPON_TIMING[VON_WEAPON_TIMING_FIGHTERS][3][3] = {",
    ]
    for name in FIGHTER_ORDER:
        actions = fighters[name]["actions"]
        lines.append(f"    {{ /* {name} */")
        for weapon in WEAPON_ORDER:
            phases = actions[weapon]["phases"]
            lines.append(f"        {{{phases[0]}, {phases[1]}, {phases[2]}}},  /* {weapon.upper()} */")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("/* [fighter][weapon L,C,R] cooldown charge increment / cap (frames). */")
    for label, key in (("VON_WEAPON_COOLDOWN_INC", "cooldown_inc"),
                       ("VON_WEAPON_COOLDOWN_MAX", "cooldown_max")):
        lines.append(f"static const int {label}[VON_WEAPON_TIMING_FIGHTERS][3] = {{")
        for name in FIGHTER_ORDER:
            actions = fighters[name]["actions"]
            row = ", ".join(str(actions[w][key]) for w in WEAPON_ORDER)
            lines.append(f"    {{{row}}},  /* {name} */")
        lines.append("};")
    lines.append("")

    output = args.output or (args.godot_dir / "native/kernels/weapon_timing.h")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
