#!/usr/bin/env python3
import ctypes,os,subprocess,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
class Result(ctypes.Structure): _fields_=[("mode_address",ctypes.c_uint32),("mode_value",ctypes.c_uint32),("marker_address",ctypes.c_uint32),("marker_value",ctypes.c_uint32),("probe_call",ctypes.c_uint32),("probe_result",ctypes.c_uint32),("index_address",ctypes.c_uint32),("index_before",ctypes.c_uint32),("index_after",ctypes.c_uint32),("index_modulus",ctypes.c_uint32),("index_mask",ctypes.c_uint32),("selected_index",ctypes.c_uint32),("selected_handler",ctypes.c_uint32),("table_address",ctypes.c_uint32),("default_handler",ctypes.c_uint32),("dispatch_call",ctypes.c_uint32),("copy_source",ctypes.c_uint32),("copy_destination",ctypes.c_uint32),("copy_count",ctypes.c_uint32),("copy_stride",ctypes.c_uint32),("mode2_status_address",ctypes.c_uint32),("mode2_status_word",ctypes.c_uint32),("mode2_bit3",ctypes.c_uint32),("mode2_aux_address",ctypes.c_uint32),("mode2_bit1",ctypes.c_uint32),("mode2_result_state_address",ctypes.c_uint32),("mode2_result_state_after",ctypes.c_uint32),("mode2_warning_string",ctypes.c_uint32),("return_target",ctypes.c_uint32)]
def main():
 with tempfile.TemporaryDirectory(prefix="von-handler6-") as d:
  so=Path(d)/"x.so";subprocess.run([os.environ.get("CC","cc"),"-shared","-fPIC","-O2","-I",str(ROOT/"von/i960"),"-o",str(so),str(ROOT/"von/i960/recovered_startup_diagnostic_handler_select_f3fe0.c")],check=True);fn=ctypes.CDLL(str(so)).recovered_startup_diagnostic_handler_select_f3fe0;fn.argtypes=[ctypes.c_uint32,ctypes.c_uint32,ctypes.c_uint32,ctypes.POINTER(ctypes.c_uint32),ctypes.c_uint32,ctypes.c_uint32,ctypes.POINTER(Result)];rows=(ctypes.c_uint32*11)(*range(0x100,0x10b));out=Result();fn(0,1,10,rows,0,0,ctypes.byref(out));assert (out.index_after,out.selected_index,out.selected_handler,out.dispatch_call,out.copy_count,out.return_target)==(0,0,0x100,0xeb060,0x1a7,0xf4138);fn(1,0,2,rows,0,0,ctypes.byref(out));assert (out.index_after,out.selected_handler,out.dispatch_call)==(2,0x102,0x102);fn(2,0,2,rows,8,0,ctypes.byref(out));assert (out.mode2_bit3,out.mode2_bit1,out.mode2_result_state_after,out.mode2_warning_string)==(1,0,0,0xf3fc0);print("PASS: 0xf3fe0 startup diagnostic handler selector")
if __name__=="__main__":main()
